### ISSUE TITLE
[REVIEW] Service Group - HART_STATE_MANAGEMENT

### ISSUE THREAD

**Issue by pathakraul** [riscv-non-isa/riscv-rpmi#10]

**Comment by lftan** [comment]
In the GET_HART_STATUS service, Hart status value definitions are different from the SBI HSM extension. Suggest adding the reference link to SBI "table_hsm_states"  and remove definition table in RPMI spec

https://github.com/riscv-non-isa/riscv-sbi-doc/blob/master/src/ext-hsm.adoc#table_hsm_states

**Comment by lftan** [comment]
> In the GET_HART_STATUS service, Hart status value definitions are different from the SBI HSM extension. Suggest adding the reference link to SBI "table_hsm_states" and remove definition table in RPMI spec
> 
> https://github.com/riscv-non-isa/riscv-sbi-doc/blob/master/src/ext-hsm.adoc#table_hsm_states

Fixed in commit https://github.com/riscv-non-isa/riscv-rpmi/commit/1468ce0d67a6a7606819eb97ede73dea3e9f2b31
