### ISSUE TITLE
[REVIEW] Service Group - DEVICE_POWER

### ISSUE THREAD

**Issue by pathakraul** [riscv-non-isa/riscv-rpmi#14]

**Comment by yeongjoshua** [comment]
For the services name, can we remove redundant name "DEVICE_POWER" as it belongs to service group with the name.

GET_DEVICE_POWER_DOMAIN_ATTRIBUTES -> GET_NUM_DOMAINS
GET_DEVICE_POWER_DOMAIN_ATTRIBUTES -> GET_DOMAIN_ATTRIBUTES
SET_DEVICE_POWER_DOMAIN_STATE -> SET_DOMAIN_STATE
GET_DEVICE_POWER_DOMAIN_STATE -> GET_DOMAIN_STATE

**Comment by pathakraul** [comment]
Yes, would you like to submit the PR?

**Comment by yeongjoshua** [comment]
The service 'get fast channel addr' should have another request data of 'service id'.
We would not able to obtain whether the respond of fast channel details belongs to get/set level/limit.

**Comment by lftan** [comment]
> The service 'get fast channel addr' should have another request data of 'service id'. We would not able to obtain whether the respond of fast channel details belongs to get/set level/limit.

Fixed in commit https://github.com/riscv-non-isa/riscv-rpmi/commit/7f338d537b27c20f38453a356259e23458fe8f65
