### ISSUE TITLE
[REVIEW] Service Group - SECURE_MANAGEMENT_MODE

### ISSUE THREAD

**Issue by pathakraul** [riscv-non-isa/riscv-rpmi#16]

**Comment by lftan** [comment]
@yli147
Table 5 in Chapter 4 uses the service group name "MM_SERVICE", but chapter 4.10 uses the service group name "MANAGEMENT".
Please fix the service group name and use the consistent name in the whole documents.

**Comment by yli147** [comment]
I'd make the original wording MM_SERVICE and MANAGEMENT be consistent to SECURE_MANAAGMENT. How do you think ?
https://github.com/riscv-non-isa/riscv-rpmi/pull/33
