### ISSUE TITLE
[REVIEW] SBI MPXY Extension support in RPMI

### ISSUE THREAD

**Issue by pathakraul** [riscv-non-isa/riscv-rpmi#18]

**Comment by pathakraul** [comment]
Action Items (2024-03-21)
- [ ] Add SEE support along with MSI for notification indication.
- [ ] Mention in `sbi_mpxy_get_notification_events` that shared memory is updated only on the function call.
- [ ] Make space for the vendor/custom message protocol ids in the table.
- [ ] Add `SBI_ERR_NOT_IMPLEMENTED` error
- [ ] Add `SBI_ERR_IO` error
- [ ] Add appendix for Devicetree bindings example.

**Comment by lftan** [comment]
Need to add the policies from the discussion

**Comment by lftan** [comment]
We also need to add a MPXY-related section in RPMI spec.
