### ISSUE TITLE
Synchronization in format across specification

### ISSUE THREAD

**Issue by pathakraul** [riscv-non-isa/riscv-rpmi#37]
### Creating this issue to list the items which should have same format across the specification. Lets keep updating this list here as we find them.

1. Use of `application processor` instead of AP. Use `platform microcontroller` instead of PuC.
---

2. Every service heading should have `(service_id: 0xXY)` appended.
eg. `Service: SYSRST_GET_ATTRIBUTES (service_id: 0x02)`.
---

3. Array display format.
---

4. Bit fields must occupy defined bits from LSB side and move towards MSB. Rest of the undefined Bits must be marked as `RESERVED and must be 0`.
---

~5. Use the `*_NOT_FOUND` error code for request parameter which directly represents resource for that service group and for rest of the parameters `*_INVAL`.~
5. Use the `*INVALID_PARAM` for all parameters passed to a service if invalid or not supported. At some places if we have a specific defined error then we can use that, for example invalid address has `*INVALID_ADDR`

For example in Clock service group(get attributes service) - `clock_id` if not valid return `RPMI_ERR_NOT_FOUND` and  for rest of the parameters like `CLOCK_RATE_INDEX` in this service should be `RPMI_ERR_INVAL`.
similarly, in case of CPPC service group (probe register service), `REG_ID` must have `RPMI_ERR_NOT_FOUND` and for `HART_ID` it should be `RPMI_ERR_INVAL`

Since we have sufficient error codes and we can use for distinct error conditions

**Comment by pathakraul** [comment]
@yeongjoshua

**Comment by lftan** [comment]
For #1, also use "application processor" instead of "Application Processor" (no capital letter in the first letter), same for "Platform Microcontroller".

I can take this change.

**Comment by pathakraul** [comment]
> For # 1, also use "application processor" instead of "Application Processor" (no capital letter in the first letter), same for "Platform Microcontroller".
> 
> I can take this change and # 2 change

Leave the Base, System Reset and Suspend, since i have preparing PRs locally and have made changes for these groups

**Comment by lftan** [comment]
> > For # 1, also use "application processor" instead of "Application Processor" (no capital letter in the first letter), same for "Platform Microcontroller".
> > I can take this change and # 2 change
> 
> Leave the Base, System Reset and Suspend, since i am preparing PRs locally and have made changes for these groups

Okay. 
You want make change  #1 and #2 for these 3 service groups as well? Or I can change them after your changes get in.

**Comment by pathakraul** [comment]
> > > For # 1, also use "application processor" instead of "Application Processor" (no capital letter in the first letter), same for "Platform Microcontroller".
> > > I can take this change and # 2 change
> > 
> > 
> > Leave the Base, System Reset and Suspend, since i am preparing PRs locally and have made changes for these groups
> 
> Okay. You want make change # 1 and # 2 for these 3 service groups as well? Or I can change them after your changes get in.

Yeah, leave them completely.

**Comment by pathakraul** [comment]
@lftan @@yeongjoshua Updated another case for error code above in the description. Let know your thoughts

**Comment by lftan** [comment]
> @lftan @@yeongjoshua Updated another case for error code above in the description. Let know your thoughts

Okay. Please update

**Comment by lftan** [comment]
Item # 1 and # 2  fix in https://github.com/riscv-non-isa/riscv-rpmi/pull/42

**Comment by lftan** [comment]
For "Return Status Code", do you think we want change to "Return status code". Remove unnecessary capital letters.
@pathakraul

**Comment by lftan** [comment]
In the description of the table for each parameter, some with full stop ".", and some do not.
Suggest adding full stop "." at the end of the sentence for proper grammar.

**Comment by yeongjoshua** [comment]
@pathakraul Does the picture need to use 'Application Processor' and 'Platform Microcontroller' instead?
