### ISSUE TITLE
`SYSSUSP_SUSPEND` should allow platform-specific quiescent states, not only WFI

### ISSUE THREAD

**Issue by SiFiveHolland** [riscv-non-isa/riscv-rpmi#65]
Currently, the `SYSSUSP_SUSPEND` service description contains the following requirement:

> The application processor which called this service must enter into the WFI state by executing the WFI instruction. The platform microcontroller will transition the system to the requested SUSPEND_STATE upon the successful WFI state transition of the application processor.

However, not all implementations use the WFI instruction to enter into a quiescent state. The `HSM_HART_STOP` service allows for this flexibility:

> The hart upon successful acknowledgement can perform the final context saving if required and must enter into a quiesced state such as WFI which can be detected and allow the platform microcontroller to proceed to stop the hart. The mechanism to detect the hart quiesced state by the platform microcontroller is platform specific.

The `SYSSUSP_SUSPEND` service should be updated to use similar language.

**Comment by pathakraul** [comment]
Yes thanks @SiFiveHolland , let me raise the PR
